# Generated by Django 5.2.9 on 2025-12-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
