# Generated by Django 5.2.9 on 2025-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeJournal', '0005_recipeingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(default=1, help_text='Quantity of ingredient'),
        ),
    ]
