# Generated by Django 5.2.9 on 2026-01-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeJournal', '0006_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient', 'unit')},
        ),
    ]
