# Generated by Django 5.2.9 on 2026-01-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeJournal', '0007_alter_recipeingredient_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=1, help_text='Quantity of ingredient'),
        ),
    ]
